// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcNMLIa0N95NT0_5h7BKDHFbsCXFDMupc',
    appId: '1:220096011370:web:a0dcab05ea50d30f5efe13',
    messagingSenderId: '220096011370',
    projectId: 'pulsar-121',
    authDomain: 'pulsar-121.firebaseapp.com',
    storageBucket: 'pulsar-121.firebasestorage.app',
    measurementId: 'G-XCPV24J3Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ3XGPXS787w4ee5CpWsRUKtVdtWUSeIM',
    appId: '1:220096011370:android:fed33a3992240f115efe13',
    messagingSenderId: '220096011370',
    projectId: 'pulsar-121',
    storageBucket: 'pulsar-121.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA47_FLK-HdxMiQukuYKLLvsx9_dO55SRM',
    appId: '1:220096011370:ios:11f26689ce0c8ea25efe13',
    messagingSenderId: '220096011370',
    projectId: 'pulsar-121',
    storageBucket: 'pulsar-121.firebasestorage.app',
    iosBundleId: 'com.example.pulsar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA47_FLK-HdxMiQukuYKLLvsx9_dO55SRM',
    appId: '1:220096011370:ios:11f26689ce0c8ea25efe13',
    messagingSenderId: '220096011370',
    projectId: 'pulsar-121',
    storageBucket: 'pulsar-121.firebasestorage.app',
    iosBundleId: 'com.example.pulsar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcNMLIa0N95NT0_5h7BKDHFbsCXFDMupc',
    appId: '1:220096011370:web:f3acf53c1d7ea6075efe13',
    messagingSenderId: '220096011370',
    projectId: 'pulsar-121',
    authDomain: 'pulsar-121.firebaseapp.com',
    storageBucket: 'pulsar-121.firebasestorage.app',
    measurementId: 'G-TMYGPBLDD7',
  );
}
